### ISSUE TITLE
Spec interaction of "gamepad for chrome navigation" with Gamepad API for content

### ISSUE THREAD

**Issue by carlsmith** [w3c/gamepad#18] opened 2015-10-26 14:37 UTC
With smart TVs, games consoles, Android boxes and so on, lots of users are using joypads and remote controls to browse the Web. It's pretty clumsy, but when you only want to find an album on YouTube, it works.

On the OUYA, buttons and axes are mapped to browser controls. FireFox on Android maps the shoulder buttons to Back and Forward, and the left axes pan the page. Chromium is similar. I'm not sure the vendors intended for that, but still.

The issue is that the browser, extensions and webapps all want to use the same pad, but the API provides no way to 'take' or 'free' a pad.

Once an app has access to a joypad, the browser will (must) just ignore the state of the pad for so long as the app can reference that pad. It can become impossible for the user to exit an app when the only input device they have to hand must be completely ignored by the browser. Users often want to keep the app open too.

The thing is, the remote controls on smartTVs are also likely to become more like gamepads. You can't play games on a typical TV remote. In a few years, using 'gamepads' to control a browser could be as ordinary as mobile or desktop. TV-friendly sites are almost inevitable, but TV-friendly browsers are impossible, because that would break all the games that use the Gamepad API.

Currently, no extension or browser can respond to a remote control without conflicting with any other extension that does so, and the Web. To the extent that we can't break the Gamepad API, we can never use control pads in extensions, or use them to control the browser.

Unless something very clever can be done (which I don't think it can, because the issue is fundamental), the Gamepad API will need to be deprecated. We can't allow billions of TV users to have a clunky or unworkable experience to save the current Gamepad API.

If the API is not removed from each browser's Extensions API, then the first extension that uses it will break all the games that use the API for every user of the extension. The current API seems to work
because it assumes that no one will ever use the Gamepad API in an extension. As soon as people do, the games will break. If an extension maps X to Refresh Page, then any game that maps X to Fire Rocket will not work for any user of the extension. The game will still fire the rocket, but the extension will also refresh the page. The API is not thread-safe, despite different 'threads' having access to the same physical pad at the same time.

Even if the API is removed from extensions, browsers can never offer first-class support for remote controls for the exact same reason as extensions. If extensions and browsers can not respond to remote controls, then they are not able to take direct input from the user of a TV.

I have ideas for how to fix it, but there are lots of clever people that will have their own take on this once they understand the issue, so I'll save my stuff for now. The point is that none of the ideas are going to be backwards-compatible, so there is some urgency here.

I am sorry if this all comes across as a bit loud. I had a heated exchange in email yesterday with someone who took a lot of convincing, so perhaps I expect more push-back than I should.

**Comment by balazs** [comment] 2015-11-08 04:36
If I understand your claims correctly, you are saying the problem is that because gamepad data is polled instead of delivered as events, users of the api are not stopped from acting upon input even though they are not having focus. Is that correct?

**Comment by carlsmith** [comment] 2015-11-08 16:31
Exactly. Yep. The fundamental design issue is that multiple 'threads' reference|poll the state of the pad without coordination.

You could use an event based system to provide coordination, but it wouldn't be entirely backwards compatible with the API people are currently using.

**Comment by pyalot** [comment] 2015-11-10 11:04
Note that eventing does not work for axes. For instance, suppose you have an X/Y axis. You interprete those axies as a cursor and use its position to draw on a canvas. What you want to get is a line connecting the current to the next cursor position at each interval. However, with events, what you will get is a staircase.

The reason is that first you receive the event for the X axis, so you move the cursor by that and draw a line, then you receive the event for the Y axis, move the cursor and draw a line --> a staircase.

The typical way to handle this (in native applications) is poll all the input events (until the queue is empty) and collate all values into an axis state object holding the X and Y value.

However in a browsers "event" interpretation, JS has no control over polling. So there's no way a JS program can synchronize its drawing loop with its event polling loop.

**Comment by balazs** [comment] 2015-11-12 19:26
I don't think we should move to the direction of events. Perhaps we should disallow the api in some form when it is used without the app having focus, i.e. returning a "null" value or even throwing an exception.

**Comment by carlsmith** [comment] 2015-11-12 19:42
That will break existing code though. If we can break compatability, I'd have a stack per pad, with the browser on the bottom. Apps would 'take' a pad, and get pushed to the stack, and 'drop' the pad when they are done, and get popped off the stack for that pad. Whoever is on top of a stack has the pad all to themselves. An extension could take from the browser and still let the Web take the pad from the extension, and just wait for the webapp to drop it again. It seems like a better basis for the API.

**Comment by pyalot** [comment] 2015-11-12 19:51
@balazs events are necessary for buttons because it's possible to miss a button press.

**Comment by toji** [comment] 2015-11-16 19:33
(Forgive me if I retread a bit of ground here, I'm still organizing my thoughts on the matter.)

This issue has come up in various forms a few times, with @pyalot specifically bringing up the issue with gamepads as the primary navigation method on consoles. (And I apologize for not having the time to adequately respond to those concerns.) The extension issue is certainly an interesting wrinkle, but I feel like it's still fundamentally the same problem: The gamepad needs the ability to work both as a navigation device AND a traditional gamepad, but not at the same time.

Browser history has shown us that ~0 developers will revisit previously published sites to update their code. Give that, a solution to this issue that allows existing pages to work on devices with this conflict would be ideal, and we should examine any possible options in that direction first. If it turns out to be infeasible, however, then a breaking change is preferable to never working at all.

The first thing that comes to mind is that gamepad-navigated devices (hereafter referred to as "consoles" for convenience) could reserve a button (Like the XBox button) that acts as the "escape hatch", like `Esc` for pointer lock. The button isn't accessible to the gamepad API directly, and any time the user presses it the gamepad API stops receiving values and control reverts back to the page. To the page this could appear to be gamepad connected and disconnected events. Seems like an interesting compromise, and has the benefit of allowing the UA to do what's most natural for the platform without page intervention. But there's problems too: Most gamepad-enabled pages will start polling for gamepad events right away and continue polling throughout the lifetime of the page. That makes the poll a bad proxy for a gamepad "lock" request, and means that once the gamepad focus has been taken back by the page there's no natural way for the page to indicate it wants to re-acquire the input. The dedicated button mentioned before could act as a toggle, but that would actually indicate it should be something other than the Xbox/PS button because you expect that pushing that when the controller is being used to navigate should return "up" a level to OS navigation and not "down" to deeper page control. Plus placing the mode switch entirely in the users hand's is undiscoverable and awkward: You'd end up tapping the "gamepad lock" button on every page just to see if it works. So that idea seems dead in the water.

So what we really want is a way for the page to explicitly say "I want to take control now" and make sure the UA can always logically escape that, notifying the page of when the input becomes locked and unlocked. We already have this for mouse events: [PointerLock](http://www.w3.org/TR/pointerlock/). So it feels natural to simply duplicate the API for gamepads, right? Actually, it seems to me like pointer lock could function as a gamepad lock as-is on consoles. After all, when using the gamepad to navigate it is literally functioning as your pointer, regardless of whether or not it displays a mouse-like cursor. So what if on consoles the gamepad API simply doesn't return anything unless you lock the pointer. This feels like an awkward conflation of APIs, but it has some advantages: There's at least some subset of existing pages with gamepad support that _also_ use pointerlock for keyboard/mouse input, and those pages don't generally stop polling for gamepad events just because the pointer is locked. (See http://phoboslab.org/xibalba/ for an example of the type of content I'm talking about.) So while we don't get every existing page working on consoles we pick up some percentage of them by happy accident, plus we've provided a clear route forward for pages that want to work on consoles. Device that don't use gamepads as a navigation device (desktop, mobile) continue to work as-is. That seems like a reasonable compromise to me, though it's actually on the console makers to implement it. At least we could spec the behavior out.

_But_ it seems like that doesn't address the extension case, and frankly I'm not sure how we can reasonably address it. I suppose the canonical example here would be a desktop extension that allows  you to navigate the browser with the gamepad as @carlsmith alluded to. Shoulder buttons to switch tabs, back button to refresh, "A" to click links. That sort of thing. It feels nonsensical to have such an API use pointerlock, especially because it would have the side effect on desktops of hiding the mouse cursor. However, we also have the benefit of allowing different API surface in extensions than pages due to the different permissions model. So it feels like extensions could gain their own "gamepad lock", accompanied by an explicit "gamepad unlock" call. While an extension has the gamepad locked no other page or extension can receive gamepad events (Multiple competing extensions would probably just follow a first-to-lock rule, but could be notified if the reason their lock failed was another extension holding the lock to communicate issues to the user.) The extension can then implement it's own version of the "escape hatch" method described above, designating whatever method they see fit for allowing the page to start/stop seeing gamepad inputs. This doesn't effect the existing gamepad API at all, since it's extension-only.

So that's all a little cobbled together, but it strikes me as a better path than declaring API bankruptcy and focusing on a 2.0 API instead. Thoughts?

**Comment by pyalot** [comment] 2015-11-16 19:52
I'm not sure I like the idea of using pointerlock to exclusively acquire all HIDs attached to a machine. Wouldn't that also imply keyboard lock as well? So it'd really be lock \o_ all the things. A notorious trouble with pointerlock is that it becomes impossible to interact with the DOM because appropriate synthesized events aren't picked up correctly by UAs. If you lock all the things, this problem would start to extend to all things, so it becomes impossible to interact with the DOM from a keyboard or gamepad as well. And although you can release lock to get interaction going, this has its own set of problems such as that UAs decide to show/reshow/reshow/reshow/reshow a dialog to advertise the fact that you've now gone "locked" which essentially bans the "area" where browsers show that dialog from any UI as the user couldn't interact with it while the dialog overlays it.

**Comment by toji** [comment] 2015-11-16 20:53
As a general rule I agree, but it's worth noting that I'm only suggesting the pointer lock abuse for platforms where the gamepad _is_ the pointer device. I don't think it's appropriate anywhere else.

**Comment by pyalot** [comment] 2015-11-16 22:19
What about other HIDs (like a steering wheel or joystick) also attached to the console? It's usually the case that they emulate a gamepad and people usually have the primary gamepad and any additional device plugged in.

**Comment by toji** [comment] 2015-11-16 22:22
This is where my lack of familiarity with modern consoles fails me: If you plug in a steering wheel or joystick controller are those treated differently by the system than a standard pad? Can you navigate a page with them? I know from a PC's perspective it's all generally the same thing: just a collection of axes and buttons.

**Comment by pyalot** [comment] 2015-11-16 22:27
Should test that.

**Comment by luser** [comment] 2016-08-01 13:48
The summary here was misleading, this has nothing to do with "thread safety", it's about a "GamepadLock" similar to PointerLock for devices like consoles where the device uses the gamepad to navigate the chrome, and content wants to use the Gamepad API for its own purposes.

**Comment by luser** [comment] 2016-08-01 13:50
This has come up before, it's listed here:
https://github.com/w3c/gamepad/blob/gh-pages/FeatureRequests.md

with some previous discussion on the mailing list:
http://lists.w3.org/Archives/Public/public-webapps/2014JanMar/0515.html
http://lists.w3.org/Archives/Public/public-webapps/2014JanMar/0685.html

**Comment by marcoscaceres** [comment] 2021-06-10 23:56
This might be best handled with with the pointer lock API. Also, for privacy reasons, you shouldn't be able to detect that you are using a gamepad as an input device/pointer. Closing as no further action is needed.

**Closed as completed by marcoscaceres** 2021-06-10 23:56 UTC
Labels: v2
