### ISSUE TITLE
Add a Project Description and Project URL

### ISSUE THREAD

**Issue by cvan** [w3c/gamepad#29] opened 2016-07-30 08:23 UTC
I would recommend adding a description ("Gamepad API") and a URL ("https://w3c.github.io/gamepad/"):

![image](https://cloud.githubusercontent.com/assets/203725/17269091/170b7964-55f4-11e6-94f4-2dc1f181fd89.png)

(I would do this, but I don't have access. /cc @sgraham @luser.)

**Comment by luser** [comment] 2016-08-01 13:34
I don't actually have admin rights on this repo. I think we need @AFBarstow.

**Comment by luser** [comment] 2016-08-01 13:45
You filed a dupe of your own issue: https://github.com/w3c/gamepad/issues/16 :)

**Closed as completed** 2016-08-01 13:45 UTC

**Comment by siusin** [comment] 2016-08-01 15:16
@cvan It'd be great to have you in the "w3c/webplatform" team, who has "write" access to most of the WebPlatform WG specs (e.g. gamepad). For IPR reasons, we will need these git team members to be part of the WG. Do you mind [joining](https://www.w3.org/2004/01/pp-impl/83482/join) the W3C [WebPlat](https://www.w3.org/WebPlatform/WG/) WG?

Please let us know in case of questions. /cc @LJWatson

**Comment by cvan** [comment] 2016-08-02 12:19
done, thanks!
