### ISSUE TITLE
button presses can be missed

### ISSUE THREAD

**Issue by pyalot** [w3c/gamepad#2] opened 2015-04-09 15:01 UTC
It is possible (and not too uncommon @ 60hz) to miss a button press. The underlying OS-APIs do provide accurate press/release events. It should be possible to install event handlers on a gamepad to capture these events.

**Comment by luser** [comment] 2015-04-24 11:13
This would be fixed by https://github.com/w3c/gamepad/issues/4

**Comment by pyalot** [comment] 2015-04-24 17:49
That's correct.

**Comment by nondebug** [comment] 2021-06-10 23:29
Closing as duplicate of #4

**Closed as completed by nondebug** 2021-06-10 23:29 UTC
